package pharmacy_system.storage.pharmacy_operations;

import pharmacy_system.model.pharmacy_operations.*;
import pharmacy_system.storage.security_user.SqliteDatabase;
import java.sql.*; import java.time.LocalDate; import java.util.*;

/** SQLite-backed batch inventory repository; stock changes and their audit movement commit atomically. */
public final class SqliteInventoryStorage implements InventoryStorage {
 private final SqliteDatabase db; public SqliteInventoryStorage(SqliteDatabase db){this.db=db;}
 public InventoryItem create(InventoryItem i){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement("INSERT INTO inventory_items(medicine_id,batch_number,expiry_date,quantity_on_hand,reorder_level,version) VALUES(?,?,?,?,?,1)",Statement.RETURN_GENERATED_KEYS)){bind(s,i);s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){k.next();return findById(k.getLong(1)).orElseThrow();}}catch(SQLException e){throw fail(e);}}
 public Optional<InventoryItem> findById(long id){return find("SELECT * FROM inventory_items WHERE inventory_id=?",id);} public List<InventoryItem> findByMedicineId(long id){return list("SELECT * FROM inventory_items WHERE medicine_id=? ORDER BY expiry_date",id);} private Optional<InventoryItem> find(String q,long id){List<InventoryItem>x=list(q,id);return x.isEmpty()?Optional.empty():Optional.of(x.get(0));} public List<InventoryItem> listAll(){return list("SELECT * FROM inventory_items ORDER BY inventory_id",null);} private List<InventoryItem> list(String q,Long id){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement(q)){if(id!=null)s.setLong(1,id);try(ResultSet r=s.executeQuery()){List<InventoryItem>x=new ArrayList<>();while(r.next())x.add(row(r));return x;}}catch(SQLException e){throw fail(e);}}
 public boolean update(InventoryItem i,long v){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement("UPDATE inventory_items SET medicine_id=?,batch_number=?,expiry_date=?,quantity_on_hand=?,reorder_level=?,version=version+1 WHERE inventory_id=? AND version=?")){bind(s,i);s.setLong(6,i.getInventoryId());s.setLong(7,v);return s.executeUpdate()==1;}catch(SQLException e){throw fail(e);}} public boolean delete(long id){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement("DELETE FROM inventory_items WHERE inventory_id=?")){s.setLong(1,id);return s.executeUpdate()==1;}catch(SQLException e){throw fail(e);}}
 public boolean deductInventory(Map<Long,Integer> plan,StockMovement m){try(Connection c=db.connection()){c.setAutoCommit(false);for(var e:plan.entrySet()){try(PreparedStatement s=c.prepareStatement("UPDATE inventory_items SET quantity_on_hand=quantity_on_hand-?,version=version+1 WHERE inventory_id=? AND quantity_on_hand>=?")){s.setInt(1,e.getValue());s.setLong(2,e.getKey());s.setInt(3,e.getValue());if(s.executeUpdate()!=1){c.rollback();return false;}}}movement(c,m);c.commit();return true;}catch(SQLException e){throw fail(e);}} public boolean adjustStock(InventoryItem i,StockMovement m,long v){try(Connection c=db.connection()){c.setAutoCommit(false);if(!update(c,i,v)){c.rollback();return false;}movement(c,m);c.commit();return true;}catch(SQLException e){throw fail(e);}}
 private boolean update(Connection c,InventoryItem i,long v)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE inventory_items SET medicine_id=?,batch_number=?,expiry_date=?,quantity_on_hand=?,reorder_level=?,version=version+1 WHERE inventory_id=? AND version=?")){bind(s,i);s.setLong(6,i.getInventoryId());s.setLong(7,v);return s.executeUpdate()==1;}} private static void movement(Connection c,StockMovement m)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO stock_movements(inventory_id,medicine_id,movement_type,quantity_delta,balance_after,reason,performed_by,created_at) VALUES(?,?,?,?,?,?,?,?)")){s.setLong(1,m.getInventoryId());s.setLong(2,m.getMedicineId());s.setString(3,m.getMovementType().name());s.setInt(4,m.getQuantityDelta());s.setInt(5,m.getBalanceAfter());s.setString(6,m.getReason());s.setLong(7,m.getPerformedBy());s.setString(8,m.getCreatedAt().toString());s.executeUpdate();}}
 public List<Map<String,Object>> queryForReport(Map<String,String> ignored){List<Map<String,Object>>x=new ArrayList<>();for(InventoryItem i:listAll()){Map<String,Object>r=new HashMap<>();r.put("inventoryId",i.getInventoryId());r.put("medicineId",i.getMedicineId());r.put("batchNumber",i.getBatchNumber());r.put("expiryDate",i.getExpiryDate());r.put("quantityOnHand",(long)i.getQuantityOnHand());r.put("isExpired",i.isExpired());x.add(r);}return x;} private static void bind(PreparedStatement s,InventoryItem i)throws SQLException{s.setLong(1,i.getMedicineId());s.setString(2,i.getBatchNumber());s.setString(3,i.getExpiryDate().toString());s.setInt(4,i.getQuantityOnHand());s.setInt(5,i.getReorderLevel());} private static InventoryItem row(ResultSet r)throws SQLException{return new InventoryItem(r.getLong("inventory_id"),r.getLong("medicine_id"),r.getString("batch_number"),LocalDate.parse(r.getString("expiry_date")),r.getInt("quantity_on_hand"),r.getInt("reorder_level"),r.getLong("version"));} private static IllegalStateException fail(SQLException e){return new IllegalStateException("Could not persist inventory",e);}
}
