package pharmacy_system.storage.pharmacy_operations;

import pharmacy_system.model.pharmacy_operations.Medicine;
import pharmacy_system.storage.security_user.SqliteDatabase;
import java.sql.*; import java.util.*;

/** SQLite-backed medicine master-data repository. */
public final class SqliteMedicineStorage implements MedicineStorage {
    private final SqliteDatabase db; public SqliteMedicineStorage(SqliteDatabase db){this.db=db;}
    public Medicine create(Medicine m){String q="INSERT INTO medicines(medicine_code,medicine_name,generic_name,dosage_form,strength,unit,description,active,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1)";try(Connection c=db.connection();PreparedStatement s=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){bind(s,m);s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){k.next();return findById(k.getLong(1)).orElseThrow();}}catch(SQLException e){throw fail(e);}}
    public Optional<Medicine> findById(long id){return find("SELECT * FROM medicines WHERE medicine_id=?",id);} public Optional<Medicine> findByCode(String code){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement("SELECT * FROM medicines WHERE medicine_code=?")){s.setString(1,code);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(row(r)):Optional.empty();}}catch(SQLException e){throw fail(e);}}
    private Optional<Medicine> find(String q,long id){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement(q)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(row(r)):Optional.empty();}}catch(SQLException e){throw fail(e);}}
    public boolean update(Medicine m,long v){String q="UPDATE medicines SET medicine_code=?,medicine_name=?,generic_name=?,dosage_form=?,strength=?,unit=?,description=?,active=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE medicine_id=? AND version=?";try(Connection c=db.connection();PreparedStatement s=c.prepareStatement(q)){bind(s,m);s.setLong(9,m.getMedicineId());s.setLong(10,v);return s.executeUpdate()==1;}catch(SQLException e){throw fail(e);}}
    public boolean delete(long id){try(Connection c=db.connection();PreparedStatement s=c.prepareStatement("DELETE FROM medicines WHERE medicine_id=?")){s.setLong(1,id);return s.executeUpdate()==1;}catch(SQLException e){throw fail(e);}}
    public List<Medicine> listAll(){return list("SELECT * FROM medicines ORDER BY medicine_id");} public List<Medicine> listActive(){return list("SELECT * FROM medicines WHERE active=1 ORDER BY medicine_id");}
    private List<Medicine> list(String q){try(Connection c=db.connection();Statement s=c.createStatement();ResultSet r=s.executeQuery(q)){List<Medicine> x=new ArrayList<>();while(r.next())x.add(row(r));return x;}catch(SQLException e){throw fail(e);}}
    public List<Map<String,Object>> queryForReport(Map<String,String> ignored){List<Map<String,Object>> x=new ArrayList<>();for(Medicine m:listAll()){Map<String,Object> r=new HashMap<>();r.put("medicineId",m.getMedicineId());r.put("medicineCode",m.getMedicineCode());r.put("medicineName",m.getMedicineName());r.put("genericName",m.getGenericName());r.put("dosageForm",m.getDosageForm());r.put("strength",m.getStrength());r.put("active",m.isActive());x.add(r);}return x;}
    private static void bind(PreparedStatement s,Medicine m)throws SQLException{s.setString(1,m.getMedicineCode());s.setString(2,m.getMedicineName());s.setString(3,m.getGenericName());s.setString(4,m.getDosageForm());s.setString(5,m.getStrength());s.setString(6,m.getUnit());s.setString(7,m.getDescription());s.setInt(8,m.isActive()?1:0);} private static Medicine row(ResultSet r)throws SQLException{return new Medicine(r.getLong("medicine_id"),r.getString("medicine_code"),r.getString("medicine_name"),r.getString("generic_name"),r.getString("dosage_form"),r.getString("strength"),r.getString("unit"),r.getString("description"),r.getInt("active")!=0,r.getLong("version"));} private static IllegalStateException fail(SQLException e){return new IllegalStateException("Could not persist medicine",e);}
}
