<%@ page contentType="text/html;charset=UTF-8" %><!doctype html><html lang="en"><head><%@ include file="../fragments/head.jspf" %></head>
<body class="auth-page"><main class="auth-workspace"><div class="auth-brand" aria-label="PharmaCare"><span class="brand-logo" aria-hidden="true">+</span><span class="brand-name">PharmaCare</span></div><section class="card auth-card" aria-labelledby="reset-title"><div class="card-body"><header class="auth-heading"><h1 id="reset-title" class="page-title">Reset password</h1><p class="page-subtitle">Choose a secure replacement for your account password.</p></header>
  <c:if test="${not empty resetError}"><div class="alert alert-danger" role="alert">${resetError}</div></c:if>
  <form class="form-grid auth-form" method="post" action="${pageContext.request.contextPath}/password/reset" data-submit-lock><%@ include file="../fragments/csrf.jspf" %><input type="hidden" name="token" value="${token}">
    <div class="field"><label for="newPassword">New password</label><div class="input-with-action"><input id="newPassword" name="newPassword" type="password" autocomplete="new-password" aria-describedby="newPassword-hint${not empty newPasswordError ? ' newPassword-error' : ''}" class="${not empty newPasswordError ? 'input-error' : ''}"><button class="btn btn-secondary" type="button" data-password-toggle="newPassword">Show</button></div><span id="newPassword-hint" class="muted">Use at least eight characters.</span><c:if test="${not empty newPasswordError}"><div id="newPassword-error" class="field-error">${newPasswordError}</div></c:if></div>
    <div class="field"><label for="confirmPassword">Confirm new password</label><div class="input-with-action"><input id="confirmPassword" name="confirmPassword" type="password" autocomplete="new-password" aria-describedby="${not empty confirmPasswordError ? 'confirmPassword-error' : ''}" class="${not empty confirmPasswordError ? 'input-error' : ''}"><button class="btn btn-secondary" type="button" data-password-toggle="confirmPassword">Show</button></div><c:if test="${not empty confirmPasswordError}"><div id="confirmPassword-error" class="field-error">${confirmPasswordError}</div></c:if></div>
    <button class="btn btn-primary auth-submit" type="submit">Reset Password</button></form>
  <div class="auth-secondary"><a href="${pageContext.request.contextPath}/login">Back to sign in</a></div>
</div></section><p class="auth-footnote">Secure pharmacy inventory and prescription management</p></main></body></html>
