package pharmacy_system.storage.management_dss;

import pharmacy_system.model.management_dss.Report;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Storage contract for Report entities.
 * Supports CRUD operations for persisted report snapshots.
 * Reports are immutable read-only snapshots persisted at generation time; no updates occur after creation.
 * Implements optimistic concurrency control via version fields (mostly for consistency).
 */
public interface ReportStorage {

    /**
     * Creates and persists a new Report snapshot.
     * The Report data is stored as a minified JSON snapshot and is immutable after creation.
     * @param report the Report to create (must have reportType, criteria, generatedBy, and data set)
     * @return the created Report with assigned reportId and version set to 1
     */
    Report create(Report report);

    /**
     * Retrieves a Report by its unique ID.
     * @param reportId the report ID
     * @return Optional containing the Report if found, empty otherwise
     */
    Optional<Report> findById(long reportId);

    /**
     * Retrieves all Reports (for listing, discovery).
     * @return a list of all Reports in the system
     */
    List<Report> listAll();

    /**
     * Retrieves all Reports of a specific type (e.g., "Prescription", "Dispensing", "Inventory", "UserAccess").
     * @param reportType the type of report to filter by
     * @return a list of Reports matching the given type
     */
    List<Report> listByType(String reportType);

    /**
     * Retrieves all Reports generated within a date range.
     * @param startDate the start date (inclusive)
     * @param endDate the end date (inclusive)
     * @return a list of Reports generated during this date range
     */
    List<Report> listByDateRange(LocalDate startDate, LocalDate endDate);

    /**
     * Retrieves all Reports generated by a specific user.
     * @param generatedBy the user ID who generated the reports
     * @return a list of Reports generated by this user
     */
    List<Report> listByGeneratedBy(long generatedBy);

    /**
     * Deletes a Report by ID.
     * @param reportId the report ID to delete
     * @return true if deletion succeeds, false if the report does not exist
     */
    boolean delete(long reportId);
}
