package pharmacy_system.controller.patient_information;

import pharmacy_system.controller.common.SessionController;
import pharmacy_system.model.patient_information.Notification;
import pharmacy_system.storage.patient_information.NotificationStorage;

import java.util.Objects;
import java.util.List;
import java.util.Comparator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import pharmacy_system.view.common.Flash;

/**
 * Manages the generation, de-duplication, delivery tracking, and persistence
 * of patient-facing notifications triggered by prescription and dispensing
 * domain events [UCD-03].
 *
 * <p>Implements Algorithm 6 (Notification de-duplication with independent
 * transaction handling) from the design document. This controller processes
 * domain events (e.g., prescription issued, medication dispensed) into
 * persisted notifications with independent delivery outcome tracking.
 *
 * <p>Key invariants upheld:
 * <ul>
 *   <li>De-duplication (Requirement 7.3, Property 13): only one successfully
 *       delivered notification per unique (patientId, prescriptionId,
 *       eventType) key.</li>
 *   <li>Transaction independence (Requirement 7.4, Property 14): a
 *       notification delivery failure does not roll back the underlying
 *       prescription/dispensing transaction that triggered the event.</li>
 *   <li>Read-state isolation (Requirement 7.2): marking a notification read
 *       is independent of delivery outcome and occurs only on patient
 *       interaction.</li>
 * </ul>
 *
 * <p>This controller does NOT perform authentication checks or require session
 * permissions because notifications are generated by internal domain events,
 * not by direct user action. Delivery implementation (e.g., email, SMS, UI
 * display) is delegated to the View layer.
 */
@Controller
public class SendAlertsNotificationsController {

    private final NotificationStorage notificationStorage;
    private final SessionController sessionController;

    /**
     * Constructs the controller with the required storage dependency.
     *
     * @param notificationStorage the storage implementation for persisting
     *                            notifications
     * @throws NullPointerException if notificationStorage is null
     */
    public SendAlertsNotificationsController(NotificationStorage notificationStorage) {
        this(notificationStorage, null);
    }

    @Autowired
    public SendAlertsNotificationsController(NotificationStorage notificationStorage,
                                              SessionController sessionController) {
        this.notificationStorage = Objects.requireNonNull(
                notificationStorage,
                "notificationStorage must not be null");
        this.sessionController = sessionController;
    }

    /**
     * Publishes a domain event that may trigger notification creation. This is
     * the entry point called by other controllers (e.g., ManagePrescriptionController,
     * DispenseMedicationController) when prescription or fulfilment state changes
     * occur.
     *
     * <p>This method evaluates whether the event type is eligible for
     * notification (Requirement 7.5) and delegates to
     * {@link #processNotification(String, long, long, String, boolean)} for
     * further processing (Requirement 7.1).
     *
     * <p>If the event type is not supported, it is silently ignored and no
     * notification is created.
     *
     * @param eventType        the event type (e.g., "MEDICATION_DISPENSED")
     * @param prescriptionId   the associated prescription's identifier
     * @param patientId        the recipient patient's identifier
     * @param recipient        the delivery target (e.g., email address or
     *                         contact method) for this notification; may be
     *                         null or empty if patient account is inactive
     * @param patientActive    {@code true} if the patient account is active
     *                         and eligible for notifications; {@code false}
     *                         if the patient is inactive or the account does
     *                         not have login access
     * @throws NullPointerException if eventType is null
     */
    public void publishDomainEvent(
            String eventType,
            long prescriptionId,
            long patientId,
            String recipient,
            boolean patientActive) {

        Objects.requireNonNull(eventType, "eventType must not be null");

        // Requirement 7.5: reject unsupported events without creating a notification
        if (!Notification.isSupportedEventType(eventType)) {
            // Event is not eligible for notification; silently ignore
            return;
        }

        // Event is eligible; proceed to notification processing
        processNotification(eventType, prescriptionId, patientId, recipient, patientActive);
    }

    /**
     * Processes an eligible notification event through de-duplication and
     * delivery tracking (Algorithm 6 from design.md).
     *
     * <p>Implements the following invariants:
     * <ul>
     *   <li>De-duplication (Requirement 7.3, Property 13): if a notification
     *       with the same deduplication key already exists, this notification
     *       is suppressed and the existing one is retained.</li>
     *   <li>Recipient validation (Requirement 7.4): if the patient account is
     *       inactive or the recipient is invalid, the notification is marked
     *       as undeliverable and persisted anyway, without blocking the
     *       underlying transaction.</li>
     *   <li>Independent persistence (Requirement 7.4, Property 14): delivery
     *       failures are recorded in the notification but never cause the
     *       underlying prescription/dispensing transaction to be rolled back.</li>
     * </ul>
     *
     * <p>The notification is persisted in all cases where it reaches this
     * method; failure during delivery does not prevent persistence.
     *
     * @param eventType        the event type (pre-validated by
     *                         {@link #publishDomainEvent})
     * @param prescriptionId   the associated prescription's identifier
     * @param patientId        the recipient patient's identifier
     * @param recipient        the delivery target; may be null or empty
     * @param patientActive    {@code true} if the patient is active and
     *                         eligible; {@code false} otherwise
     */
    public void processNotification(
            String eventType,
            long prescriptionId,
            long patientId,
            String recipient,
            boolean patientActive) {

        // Algorithm 6 Step 1: derive the deduplication key
        String deduplicationKey = Notification.buildDeduplicationKey(
                patientId, prescriptionId, eventType);

        // Algorithm 6 Step 2: check for duplicate (Requirement 7.3, Property 13)
        if (notificationStorage.existsByDeduplicationKey(deduplicationKey)) {
            // Duplicate detected; suppress creation and retain the existing notification
            return;
        }

        // Algorithm 6 Step 3: create a new notification in unread state
        // (Requirement 7.1)
        Notification notification = createNotificationForEvent(
                eventType, prescriptionId, patientId, recipient);

        // Algorithm 6 Step 4: validate recipient eligibility (Requirement 7.4)
        if (!notification.validateRecipient(patientActive)) {
            // Patient is inactive or recipient is invalid; mark as undeliverable
            // but still persist the notification
            notification.markNotDeliverable(
                    patientActive
                            ? "Invalid or missing recipient"
                            : "Inactive patient account");
            notificationStorage.create(notification);
            return;
        }

        // Algorithm 6 Step 5: attempt delivery (Requirement 7.4)
        // Delivery is delegated to the View layer; this controller simulates
        // a delivery attempt and records the outcome. In a real implementation,
        // the View layer would handle actual delivery (email, SMS, etc.).
        boolean deliverySuccess = attemptDelivery(notification);

        if (deliverySuccess) {
            notification.markDelivered();
        } else {
            notification.markDeliveryFailed("Delivery failed (see logs for details)");
        }

        // Algorithm 6 Step 6: persist the notification with its delivery outcome
        // (Requirement 7.4, Property 14). Persistence failure is logged but never
        // rolls back the underlying transaction.
        try {
            notificationStorage.create(notification);
        } catch (Exception e) {
            // Delivery failure or persistence failure must not reverse the
            // underlying transaction (Requirement 7.4, Property 14). Log the
            // failure and proceed.
            System.err.println(
                    "Failed to persist notification: " + e.getMessage());
        }
    }

    /**
     * Marks a specific notification as read by the patient (Requirement 7.2).
     * The read state is persisted independently of the delivery outcome.
     *
     * <p>Calling this method on an already-read notification has no effect;
     * the original read timestamp is retained.
     *
     * <p>This method uses optimistic concurrency control provided by the
     * storage layer. If concurrent modifications are detected, the update
     * fails and the read state is not persisted; the caller may retry.
     *
     * @param notificationId the identifier of the notification to mark as read
     * @return {@code true} if the read state was successfully persisted,
     *         {@code false} if the notification does not exist or an optimistic
     *         concurrency conflict occurred
     */
    public boolean markNotificationRead(long notificationId) {
        var notificationOpt = notificationStorage.findById(notificationId);

        if (notificationOpt.isEmpty()) {
            return false;
        }

        Notification notification = notificationOpt.get();

        // If already read, no need to persist
        if (notification.isRead()) {
            return true;
        }

        // Requirement 7.2: transition to read state only on patient interaction
        notification.markRead();

        // Persist the read state with optimistic concurrency control.
        // The storage implementation maintains version information for conflict detection.
        // We assume that a notification loaded from storage has version information
        // that the storage layer uses for optimistic locking.
        // For initial reads from storage, we use version 1 as a reasonable default.
        // The storage implementation will handle the actual version tracking and
        // return false if a concurrent modification is detected.
        return notificationStorage.update(notification, 1);
    }

    @GetMapping("/patient/notifications")
    public String notifications(Model model) {
        requirePatientSession();
        List<Notification> notifications = notificationStorage
                .findByPatientId(sessionController.getCurrentUserId()).stream()
                .sorted(Comparator.comparing(Notification::getCreatedAt).reversed())
                .toList();
        model.addAttribute("notifications", notifications);
        notificationPage(model, "Notifications");
        return "notifications/list";
    }

    @GetMapping("/patient/notifications/{id}")
    public String notification(@PathVariable long id, Model model) {
        requirePatientSession();
        var notification = notificationStorage.findById(id);
        if (notification.isEmpty() || notification.get().getPatientId() != sessionController.getCurrentUserId()) {
            return "errors/not-found";
        }
        model.addAttribute("notification", notification.get());
        notificationPage(model, "Notification detail");
        return "notifications/detail";
    }

    @PostMapping("/patient/notifications/{id}/read")
    public String markRead(@PathVariable long id, RedirectAttributes redirect) {
        requirePatientSession();
        var notification = notificationStorage.findById(id);
        if (notification.isEmpty() || notification.get().getPatientId() != sessionController.getCurrentUserId()) {
            return "redirect:/patient/notifications";
        }
        markNotificationRead(id);
        redirect.addFlashAttribute("flash", new Flash("success", "Notification marked as read."));
        return "redirect:/patient/notifications/" + id;
    }

    private void requirePatientSession() {
        if (sessionController == null) throw new SessionController.SessionExpiredException("No web session");
        sessionController.requirePermission("VIEW_NOTIFICATIONS");
    }

    private void notificationPage(Model model, String title) {
        model.addAttribute("title", title);
        model.addAttribute("breadcrumb", "Notifications / " + title);
    }

    /**
     * Creates a notification instance for a given event type, with appropriate
     * title and message content. This method encapsulates the event-to-notification
     * mapping logic.
     *
     * @param eventType      the event type
     * @param prescriptionId the associated prescription's identifier
     * @param patientId      the recipient patient's identifier
     * @param recipient      the delivery target
     * @return a new Notification in unread state with delivery pending
     */
    private Notification createNotificationForEvent(
            String eventType,
            long prescriptionId,
            long patientId,
            String recipient) {

        String notificationType;
        String title;
        String message;

        switch (eventType) {
            case "PRESCRIPTION_ISSUED":
                notificationType = "Clinical";
                title = "Prescription Issued";
                message = "Your prescription has been issued and is ready for preparation.";
                break;

            case "PRESCRIPTION_CANCELLED":
                notificationType = "Clinical";
                title = "Prescription Cancelled";
                message = "Your prescription has been cancelled. Please contact your healthcare provider for details.";
                break;

            case "MEDICATION_PREPARING":
                notificationType = "Pharmacy";
                title = "Medication Preparing";
                message = "Your medication is being prepared and will be ready soon.";
                break;

            case "MEDICATION_READY_FOR_COLLECTION":
                notificationType = "Pharmacy";
                title = "Medication Ready for Collection";
                message = "Your medication is ready for collection. Please visit the pharmacy at your convenience.";
                break;

            case "MEDICATION_DISPENSED":
                notificationType = "Pharmacy";
                title = "Medication Dispensed";
                message = "Your medication has been dispensed and is ready for pickup.";
                break;

            default:
                // This should not occur because the event type is pre-validated
                notificationType = "System";
                title = "Notification";
                message = "An event related to your prescription has occurred.";
                break;
        }

        return new Notification(
                0, // notificationId (0 means not yet persisted)
                patientId,
                prescriptionId,
                eventType,
                notificationType,
                title,
                message,
                recipient);
    }

    /**
     * Simulates a delivery attempt for a notification. In a real implementation,
     * this would coordinate with the View layer or an external delivery service
     * (e.g., email service, SMS provider, push notification service).
     *
     * <p>For now, this method returns {@code true} to indicate successful
     * delivery. Callers (Algorithm 6) will record the outcome in the
     * notification and persist it.
     *
     * @param notification the notification to deliver
     * @return {@code true} if delivery was successful; {@code false} otherwise
     */
    private boolean attemptDelivery(Notification notification) {
        // Placeholder: in a real implementation, this would attempt to send
        // the notification via email, SMS, or other channels.
        // For now, assume delivery always succeeds.
        return true;
    }
}
